# s1=(intinput("Enter marks of student 1:\n"))
s1 = input("Enter marks of student 1:\n")
# s2=(intinput("Enter marks of student 2:\n"))
s2 = input("Enter marks of student 2:\n")
# s3=(intinput("Enter marks of student 3:\n"))
s3 = input("Enter marks of student 3:\n")
# s4=(intinput("Enter marks of student 4:\n"))
s4 = input("Enter marks of student 4:\n")
# s5=(intinput("Enter marks of student 5:\n"))
s5 = input("Enter marks of student 5:\n")
# s6=int(input("Enter marks of student 6:\n"))
s6 = input("Enter marks of student 6:\n")
students_marks = [int(s1), int(s2), int(s3), int(s4), int(s5), int(s6)]
students_marks.sort()
print(students_marks)
